package com.kkoemets.scripts.nightmarezone.scripts;

public enum ScriptName {
    SUPER_RESTORE_AND_RANGING_POTION_MODE,
    ABSORPTION_AND_OVERLOAD_MODE_SCRIPT,
    ABSORPTION_AND_OVERLOAD_MODE_FOR_DEF_1_PURES,
    ABSORPTION_MODE_SCRIPT
}